### ISSUE TITLE
Error when using DynamicBungeeAuth with your plugin.

### ISSUE THREAD

**Issue by RikoDEV** [lucko/BungeeGuard#10]
![image](https://user-images.githubusercontent.com/18230443/51797930-2b6c1900-220b-11e9-8050-0adacb7ec27c.png)

Waterfall: https://papermc.io/ci/job/Waterfall/251/
DBA: 10-03-BETA
BungeeGuard: latest

PaperSpigot: https://papermc.io/ci/job/Paper-1.13/509/

**Comment by lucko** [comment]
Probably something you need to ask the author of DynamicBungeeAuth to support.

I'd guess it is not respecting Paper's `PlayerHandshakeEvent`.
