### ISSUE TITLE
Unable to connect with 1.14.2

### ISSUE THREAD

**Issue by Kowaman** [lucko/BungeeGuard#14]
Using a 1.14.2 client I am unable to connect to a 1.14.2 server running Paper-65 1.14.2, Waterfall 1.14-SNAPSHOT:57a7f98:284, latest release (1.0-SNAPSHOT) of BungeeGuard-proxy and backend, and no other plugins.

Waterfall error:
`[23:09:35 ERROR]: [USERNAME|/IP ADDRESS] <-> ServerConnector [dev] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process! 1aa2017b227472616e736c617465223a`

Paper error:
`[23:09:35 INFO]: /IP ADDRESS:PORT lost connection: Internal Exception: java.lang.IllegalStateException: PlayerHandshakeEvent may only be triggered synchronously.`

Client error:
`Exception Connecting:QuietException: Unexpected packet received during server login process! 1aa2017b227472616e736c617465223a`

**Comment by k9lego** [comment]
1.14.2 works fine, did you update Bungeecord?

**Comment by lucko** [comment]
I think this miiight be a Paper error.

> Paper error:
[23:09:35 INFO]: /IP ADDRESS:PORT lost connection: Internal Exception: java.lang.IllegalStateException: PlayerHandshakeEvent may only be triggered synchronously.

That seems like a bug. Maybe worth reporting to the Paper devs.

**Comment by Kowaman** [comment]
Working on 1.14.4, must have been upstream.
