### ISSUE TITLE
Failed event register

### ISSUE THREAD

**Issue by ApertureDevelopment** [lucko/BungeeGuard#15]
This error happens in PaperSpigot 1.8.8-R0.1-SNAPSHOT ( git-PaperSpigot-"4c7641d" )

BungeeGuard is unable to register a event on PlayerHandshake because the class does not exist.

```
ERROR [BungeeGuard] Plugin BungeeGuard v1.0-SNAPSHOT has failed to register events for class me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin because com/destroystokyo/paper/event/player/PlayerHandshakeEvent does not exist.
```

It seems that the class exists in more recent Paper versions, but I am unable to locate a more recent 1.8.8 release of PaperSpigot with the class.

**Comment by lucko** [comment]
Yes, you're correct.

BungeeGuard doesn't work with Paper versions that old - not really much I can do about that. :/
