### ISSUE TITLE
Issue with ProtocolSupport in 1.14.4

### ISSUE THREAD

**Issue by Artuto** [lucko/BungeeGuard#16]
Hi. I'm experiencing issues with BungeeGuard in 1.14.4 with ProtocolSupport.

Using Paper 1.14.4 build 137 and ProtocolSupport build 397.

This is the error I get: https://gist.github.com/Artuto/70bbb08be3056c1b02e908ad50e73414

When I removed BungeeGuard the issue stopped.

**Comment by Artuto** [comment]
Related PS issue: https://github.com/ProtocolSupport/ProtocolSupport/issues/1134

**Comment by Artuto** [comment]
Bump @lucko

**Comment by lucko** [comment]
This is not a BungeeGuard issue.
