### ISSUE TITLE
are 1.14.4 supported? 

### ISSUE THREAD

**Issue by BenjaminHoegh** [lucko/BungeeGuard#18]
are 1.14.4 supported? or are the security fixed in bungeecord so we don't need it?

**Comment by FeaturedSpace** [comment]
Ummm. Of course, 1.14.4 is supported, and I don't think the Bungee security problems will ever be fixed.

**Comment by HappyAreaBean** [comment]
1.8.8 paper support?

**Comment by lucko** [comment]
> are 1.14.4 supported

Yes

> are the security fixed in bungeecord so we don't need it

No :)

**Comment by BenjaminHoegh** [comment]
@lucko are this also a security problem in waterfall?

**Comment by lucko** [comment]
Yes
