### ISSUE TITLE
Handler failed

### ISSUE THREAD

**Issue by TheCynicalKitty** [lucko/BungeeGuard#23]
19.12 00:16:17 [Server] ERROR Plugin BungeeGuard v1.0-SNAPSHOT has failed to register events for class me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin because com/destroystokyo/paper/event/player/PlayerHandshakeEvent does not exist.

Server is 1.8.8 any ideas

**Comment by DeveloperBoy** [comment]
The plugin does not support 1.8.8 because Paperspigot 1.8.8 has no PlayerHandshakeEvent. This should be fixed in the latest update (by using a normal Spigot event), but as you can see in #22 it's still not working.
