### ISSUE TITLE
Small question.

### ISSUE THREAD

**Issue by EnderBro123** [lucko/BungeeGuard#24]
Does this have 1.8-1.15.1 support?

**Comment by stijnb1234** [comment]
No. It supports PaperSpigot 1.9-1.15.1.

**Comment by untuned** [comment]
No 1.8.* support whatsoever?

**Comment by stijnb1234** [comment]
There was an update that fixed that, but it was removed again because it didn't work properly.

**Comment by stijnb1234** [comment]
@lucko Can be closed.

**Comment by dieterblancke** [comment]
It is possible if you manually add the PlayerHandshakeEvent to (Paper)Spigot 1.8.X (it's open source so you could do it).

That is how we run this plugin in 1.8.8 on our network currently.
Otherwise it's not possible and you would have to upgrade.
