### ISSUE TITLE
Error when a player tries to login in a server

### ISSUE THREAD

**Issue by ACrispyCookie** [lucko/BungeeGuard#25]
Hello, a player tried somehow to join my server bypassing the proxy and BungeeGuard got [this](https://pastebin.com/86HqLmgY) error and allowed the player to join. Please help me as soon as possible.

**Comment by stijnb1234** [comment]
You are using an old build of the plugin. This version contained some bugs, so it's reverted. Please download the newest build at [his jenkins](https://ci.lucko.me/job/BungeeGuard/lastSuccessfulBuild/artifact/bungeeguard-backend/target/bungeeguard-backend.jar)

**Comment by ACrispyCookie** [comment]
I have installed it, will it work on paper and normal spigot 1.8.x?

**Comment by stijnb1234** [comment]
No. Bungee Guard never worked and still doesn't work for Spigot or Paperspigot 1.8.8 because of a missing event.

**Comment by ACrispyCookie** [comment]
Now I got this message on start up, will it work?

[BungeeGuard] Enabling BungeeGuard v1.0-SNAPSHOT
> [22:06:56 INFO]: [BungeeGuard] Using Paper PlayerHandshakeEvent
> [22:06:56 ERROR]: [BungeeGuard] Plugin BungeeGuard v1.0-SNAPSHOT has failed to register events for class me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin because com/destroystokyo/paper/event/player/PlayerHandshakeEvent does not exist.

**Comment by stijnb1234** [comment]
Which Paperspigot version are you running? (/version)

**Comment by ACrispyCookie** [comment]
ElapsedSpigot which is based on PaperSpigot

**Comment by ACrispyCookie** [comment]
Also I tried on my other server which has git-PaperSpigot-"4c7641d" (MC: 1.8.8) and I got the same message

**Comment by ACrispyCookie** [comment]
Hello?

**Comment by stijnb1234** [comment]
As I already said, BungeeGuard doesn't support 1.8.8
