### ISSUE TITLE
Pinger

### ISSUE THREAD

**Issue by x1p** [lucko/BungeeGuard#27]
BungeeGuard seems to block PlaceholderAPI's Pinger.

> Pinger is an expansion which pings a server to see if it's online or offline. More information about pinger is available via https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#pinger

I've made an issue at the placeholderapi github, [here](https://github.com/PlaceholderAPI/Pinger-Expansion/issues/5) but it works fine if bungeeguard is not loaded. This makes bungeeguard as the main suspect.

To reproduce:
On the hub server, I've have a scoreboard with the appropriate placeholder. But it can easily be reproduced with a command too.
- we take a hub server and a second server
- on the hub server install placeholderAPI
- execute: `papi ecloud download Pinger` to install the pinger expansion
- execute `papi reload`
- execute `papi parse me %pinger_online_127.0.0.1:12345%` where the ip and port matches the ip and port of the second server.
- see result
- repeat above steps with/without bungeeguard.

**Comment by lucko** [comment]
Ermmm, BungeeGuard only touches the handshake, but the server list ping should be ok?

**Comment by lucko** [comment]
Definitely doesn't touch the server list ping.
