### ISSUE TITLE
Can you implement Bungee Guard on only a few Backend servers?

### ISSUE THREAD

**Issue by HahaSoStupid** [lucko/BungeeGuard#28]
Hello,

We have 3 backend servers (Lobby, Survival, Skyblock) and a proxy.

Proxy and Lobby are both in the same machine while survival and skyblock are on hosts.
Can we just implement Bungee Guard on Survival and Skyblock and don't implement in on Lobby?

Thanks in advance,
Regards.

**Comment by stijnb1234** [comment]
That doesn't make sense. You need to implement BungeeGuard on every backend server to make your network save.

**Comment by HahaSoStupid** [comment]
My lobby is protected by Firewall so it doesn't need bungee guard while my other 2 servers aren't, hence my question haha

**Comment by lucko** [comment]
It needs to be installed on all servers connected to the proxy.
