### ISSUE TITLE
BungeeGuard HandShake Event. Paper's the last and same versions using at my servers Paper-227 on lobby and survival waterfall-340 on wf server

### ISSUE THREAD

**Issue by turkeymc** [lucko/BungeeGuard#29]
https://hastebin.com/onasomahey.bash
My Server's plugin lists
Lobby: https://hizliresim.com/a0eKCm
Survival: https://hizliresim.com/03X2Y6
Waterfall: https://hizliresim.com/Lo4LY7

I want to enter the server but it doesnt accept me;
https://hizliresim.com/UjrrTJ

**Comment by stijnb1234** [comment]
I think it doesn't work with Waterfall, because it's never listed anywhere. Not sure tho.

**Comment by turkeymc** [comment]
It solved. Skinsrestorer bungee doesnt work on my waterfall.
