### ISSUE TITLE
Error on Paper 1.8.8

### ISSUE THREAD

**Issue by Eurphus** [lucko/BungeeGuard#33]
`> [04:51:36 INFO]: [BungeeGuard] Enabling BungeeGuard v1.0-SNAPSHOT
> [04:51:36 INFO]: [BungeeGuard] Using Paper PlayerHandshakeEvent
> [04:51:36 ERROR]: [BungeeGuard] Plugin BungeeGuard v1.0-SNAPSHOT has failed to register events for class me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin because com/destroystokyo/paper/event/player/PlayerHandshakeEvent does not exist.`

Is what I get when starting my server. My server is running the latest 1.8.8 paper jar from paper.io/legacy

**Comment by stijnb1234** [comment]
BungeeGuard doesn't support Paperspigot 1.8.8. Only 1.9+. 

That's because of a missing event in 1.8.8.

**Comment by Eurphus** [comment]
The release says it supports 1.8 though? Also even if not, there’s got be to some type of API or whatever to replace whatever is missing.

**Comment by stijnb1234** [comment]
There is, and that event was integrated, but it didn't work right.

**Comment by Eurphus** [comment]
If it didn’t work right, then isn’t that an issue with the plugin that needs to be fixed? Or a workaround or anything?

**Comment by Eurphus** [comment]
If not is there any way I can enable or add the working event somehow to my server, either with a modified Jar or API?

**Comment by Eurphus** [comment]
Also the release says it supports 1.8-1.12, Id recommend changing this.

**Comment by stijnb1234** [comment]
> If it didn’t work right, then isn’t that an issue with the plugin that needs to be fixed? Or a workaround or anything?

Yes, but I think the developer has no time to do that, and the creator of the PR also ignored it (or didn't do anything to fix it).

> If not is there any way I can enable or add the working event somehow to my server, either with a modified Jar or API?

By upgrading to 1.9+ and using ViaBackwards / ViaRewind (for example).

**Comment by lucko** [comment]
1.8 support has now been added.

c6ac8c1e1c8c292e1ff14ad16a91157828090690
