### ISSUE TITLE
Securty bypass with fake uuid

### ISSUE THREAD

**Issue by GaleaStefan** [lucko/BungeeGuard#35]
Hello, so recently some griefers joined our server using our staff accounts, so we checked the console to see how did they bypass the securty. This is the error we are recieving in the console when a griefer tries to join:
`[21:06:21] [Netty Epoll Server IO #0/ERROR]: Could not pass event PlayerHandshakeEvent to BungeeGuard v1.1-SNAPSHOT
java.lang.IllegalArgumentException: Invalid UUID string: Faicu
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_212]`
As far as i can tell, those griefers enter with fake uuids and because of that, BungeeGuard cannot convert the string to uuid, so it gives an error and the griefer bypasses the security. I think surrounding the string to uuid conversion with a try, catch block should fix this problem

**Comment by Laarryy** [comment]
Could ya pastebin more logs? Any extra information or if you're able to replicate it yourself and tell us how exactly would be very, very useful.

**Comment by GaleaStefan** [comment]
https://pastebin.com/QzP0SQnF
Pastebin logs

They did not connect thru the proxy, they somehow managed to connect directly to a backend server which should be impossible. I tried myself to directly connect to a server with it's ip and it kicked me(no data forwarded by the proxy). My guess is that they have a hack client which lets them change the uuid, and by inserting an invalid uuid, the plugin gives that error, which, in my teory, bypasses the security.

**Comment by stijnb1234** [comment]
Is Faicu your MC name?

**Comment by GaleaStefan** [comment]
Yes, it is (Not mine). And by directly connecting to the backend server and bypassing the bungee guard, they bypass even the login, so they don't need to insert the password to log in, which gives them full acces to op commands.

**Comment by GaleaStefan** [comment]
> Is Faicu your/anyones MC name?
> 
> **EDIT:** Okay, yes. It is. Some hacked client that doesn't send the UUID but the name in the handshake?

Yea, i think this is what they do. A try, catch block should fix this issue

**Comment by lucko** [comment]
I've pushed a fix here - https://ci.lucko.me/job/BungeeGuard/26/

I've got to head out for a bit but I will make a release / some sort of disclosure for this when I get back.

**Comment by lucko** [comment]
I've released v1.2.0 to GitHub & Spigot with a notice encouraging all users to update.

Thanks again.

**Comment by lucko** [comment]
I've removed the exact details from this issue and added some more information here.

https://github.com/lucko/BungeeGuard/blob/master/SECURITY.md
