### ISSUE TITLE
Gradle Build??? (enhancement)

### ISSUE THREAD

**Issue by c0d3rb0y** [lucko/BungeeGuard#38]
So can we have some kind of way to use gradle to build this?
Cuz idk how i'm supposed to build the jar on windows 10.

**Comment by stijnb1234** [comment]
You can build this using Maven.

**Comment by c0d3rb0y** [comment]
but wait how do i use maven to build???

**Comment by stijnb1234** [comment]
Clone the repo, and typ `mvn clean package`
