### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by Grafhugo** [lucko/BungeeGuard#39]
Hello,

Since i putted cloudflare to my domain its not working anymore
I forwarded the cloudflare to my proxy adress (port: 25577). But when i want to connect it says: Unable to authentificate - no data was forwarded by the proxy

How should I fix this?

**Comment by Anarchist-byte** [comment]
I have this problem too!

**Comment by lucko** [comment]
Make sure you are connecting via the proxy address - not directly to the backend server.

**Comment by Anarchist-byte** [comment]
> Make sure you are connecting via the proxy address - not directly to the backend server.

Thank you, it is works!
