### ISSUE TITLE
"Handshake exceeds 1000 characters"

### ISSUE THREAD

**Issue by goon1214** [lucko/BungeeGuard#48]
Users are unable to connect to the network through the proxy, but it does block direct connections to the backend servers.

The following errors are repeated for all users trying to connect:

`[19:59:57] [Netty Epoll Server IO #1/WARN]: [BungeeGuard] Denying connection from handshake exceeds 1000 characters - reason: INVALID_HANDSHAKE` (Spigot server error)

`22:05:44 [INFO] [*********] disconnected with: Kicked whilst connecting to lobby: Unable to authenticate - no data was forwarded by the proxy.` (Proxy error)

- Tested on our production server as well as a home-hosted network.

- Also tested using a clean install of the proxy and backend server (no other plugins installed, just BungeeGuard).

- Confirmed that the token is the same between the proxy and backend server, also tried using a new token by BungeeGuard.

**Proxy jar (tested with both):** _Waterfall and Bungeecord_
**Backend jar (tested with both):** _Purpur and Paper_
(Latest builds for both)

**Comment by stijnb1234** [comment]
Which plugins do you have on your proxy side?

**Comment by goon1214** [comment]
On the live proxy there are a few plugins but we tested it with a clean
install of bungee cord and waterfall on the home network (no other plugins).

**Comment by nathanfranke** [comment]
Hey I'm getting this too now. My proxy is Velocity.

**Comment by lucko** [comment]
Should be fixed in the latest release.
