### ISSUE TITLE
Not compatible with Velocity

### ISSUE THREAD

**Issue by ObscenityIB** [lucko/BungeeGuard#49]
Having trouble with another plugin and was about to try this one, but there is only one JAR to download and its only for Bungee.

`[07:03:41 ERROR]: Unable to load plugin plugins/BungeeGuard.jar`
`com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.`

Is there a Velocity version that I can't find?

**Comment by stijnb1234** [comment]
https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity

Followed these steps?

**Comment by ObscenityIB** [comment]
Yes.
But apparently I don't even need to install the plugin, it just works.

Maybe specify in those instructions that you DONT need to put the plugin on the proxy.
