### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by LuisGVE** [lucko/BungeeGuard#5]
BungeeGuard is one plugin? I need install bungeeguard proxy on bungeecord server /plugins and bungeeguard backend on spigot servers /plugins ?

The token is generated automatically? Do I need to change it?

Is the same token generated for all servers or is a different one generated randomly for each server?

Could you briefly explain the installation? Thank you very much.

**Comment by lucko** [comment]
https://github.com/lucko/BungeeGuard#installation
