### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by Billyxxdd** [lucko/BungeeGuard#51]
Hey plugin works great until today. I received this message and I cant join my own server

[BungeeGuard] Denying connection from (some numbers and characters) - reason: NO_TOKEN.
And in game it say: 
Unable to authenticate.

Please help me fix it cuz idk what to do

**Comment by iGabyTM** [comment]
Make sure there is a token in both configs.

**Comment by stijnb1234** [comment]
Provide us more info. Which plugins are you using (both proxy and backend side)? Which server software are you using?

**Comment by Allcaro22** [comment]
Hi, i have the same problem. I will connect thru the bungee on Auth server, you will log in and if you want to jump into the portal ( AdvancedPortals plugin) it will say : Minecraft - Kicked whilst connecting to (server) : Unable to authenticate, Consol - [WARN]: [BungeeGuard] Denying connection from [Numbers, characters] @ IP adress - reason: NO_TOKEN
[INFO]: /Another adress lost connection: Unable to authenticate.

**Comment by stijnb1234** [comment]
> Provide us more info. Which plugins are you using (both proxy and backend side)? Which server software are you using?

@Allcaro22 ^^

**Comment by Allcaro22** [comment]
HUB server - AdvancedPortals, SkinsRestorer, DeluxeHub, Essentials, Holograms, PermissionsEx, Plugman, Skript, TAB, Updater, ViaRewind/backwards/version, WorldEdit, WorldBorder, WorldGuard

AUTHME server - Authme, AdvancedPortals, BGuard, Worldguard, holograms. 

We are trying to solve the problem to change the bungee to waterfall,

**Comment by lucko** [comment]
Make sure BungeeGuard is installed correctly on your BungeeCord proxy.
