### ISSUE TITLE
Can't get from one server to another w/ BungeeGuard installed

### ISSUE THREAD

**Issue by Bombbery** [lucko/BungeeGuard#53]
So, recently I started up a BungeeCord network and sought out BungeeGuard as the recommended plugin to help remediate BungeeCord's vulnerabilities; However, I stumbled across an issue I feel like I just don't see a solution to even though it's very likely there. 

The proxy has BungeeGuard installed, and each of the servers connected to the proxy have it as well - alongside ProtocolLib and the token generated by the proxy in their respective config files. It works *fine*, but my issue arises when I try to switch to a different server after being connected to the default "hub" server. 

It throws the **"Unable to authenticate."** message described in the config file for BungeeGuard, and the console reads the following:
`Netty Epoll Server IO #3/WARN Denying connection from aef501dc-xxxx-xxxx-xxxx-xxxxxxxxxxxx @ x.x.x.x - (token) - reason: INCORRECT_TOKEN`

(token) being the exact same one listed in the *allowed-tokens* part of BungeeCord's config file. So, what exactly am I missing? Can you *connect* to each server, or is there a different way I don't see? I'm kinda lost, here.

**Comment by Allcaro22** [comment]
Same here, i was talking to a man, who is really good at setting up minecraft servers and he said it will probably be a mistake in a plugin

**Comment by Bombbery** [comment]
> 
> 
> Same here, i was talking to a man, who is really good at setting up minecraft servers and he said it will probably be a mistake in a plugin

I ended up just gutting the plugin, and plan on reusing it if I get an answer to figure this out.

**Comment by lucko** [comment]
Are you sure the allowed token is defined in the config correctly?

**Comment by Bombbery** [comment]
> Are you sure the allowed token is defined in the config correctly?

Yup, both of the servers had the exact token generated by the proxy

**Comment by CyberFlameGO** [comment]
I’m also having the same issue

**Comment by lucko** [comment]
Can you send a pastebin of your BungeeGuard config.yml on Spigot

**Comment by CyberFlameGO** [comment]
Sure thing, one sec

**Comment by CyberFlameGO** [comment]
https://pastebin.com/QG6s9H6F

**Comment by CyberFlameGO** [comment]
I use Travertine as my proxy software, on Java 16 (I’ve also tried Java 8 but the results were the same), for my backend (Spigot) I use Java 8 on Minecraft version 1.8.8, and use the latest dev build of ProtocolLib (I’ve also tried the latest “stable” release) which is [https://github.com/dmulloy2/ProtocolLib/commit/7ce3f471bf3bd1e1a0bf90c0da7766841c565575](commit 7ce3f47).

**Comment by Bombbery** [comment]
> 
> 
> Can you send a pastebin of your BungeeGuard config.yml on Spigot

I did a full reinstall of BungeeGuard on all my servers and that seems to have fixed my issue. Leaving open so @CyberFlameGO can get a response.
