### ISSUE TITLE
Does BungeeGuard work with backend proxy servers?

### ISSUE THREAD

**Issue by WolfyRed** [lucko/BungeeGuard#56]
I've been wondering this because I have extra proxy servers as backend to the main proxy server, which the proxy backend servers then connect to the backend spigot/paper servers...

**Comment by lucko** [comment]
No, this isn't a supported setup

(and sorry to say that the BungeeCord authors definitely don't support it either!)

**Comment by rautamiekka** [comment]
I'm curious: what good would this kinda setup do and/or what bad would it do -> not supported ?
