### ISSUE TITLE
Kicked whilst connecting to lobby: Unable to authenticate - no data was forwarded by the proxy.

### ISSUE THREAD

**Issue by Thaumi7777** [lucko/BungeeGuard#72]
Hi, I installed the GeyserMC plugin on my server, but when connecting from the bedrock version of minecraft, it gives this error. 
![image](https://user-images.githubusercontent.com/75178229/168413629-6758d681-c181-4838-b15e-12cbf3cd099c.png)

Kicked whilst connecting to lobby: Unable to authenticate - no data was forwarded by the proxy.

How to fix it?

**Comment by lucko** [comment]
Install BungeeGuard on your proxy.
