### ISSUE TITLE
Update BungeeGuard to 1.19

### ISSUE THREAD

**Issue by NoltoxGit** [lucko/BungeeGuard#74]
Hello!
It's possible to update BungeeGuard for MC 1.19 please?

I have this error on my Proxy : https://mclogs.minestrator.com/ESjHlAA

Ty!
~ Noltox ~

**Comment by fabegalo** [comment]
UP !!!

**Comment by iLuckyx** [comment]
I believe this is also related to the same issue outlined in: https://github.com/GeyserMC/Floodgate/issues/312#issuecomment-1149456001

`
Its due to bungee cord changing net.md_5.bungee.connection.LoginResult$Property to net.md_5.bungee.protocol.Property

`

**Comment by xHyroM** [comment]
I made a fork, you can install it
Install link: https://github.com/RilyEvent/BungeeGuard/suites/6847775715/artifacts/264257362
Build log: https://github.com/RilyEvent/BungeeGuard/actions/runs/2462749036

**Comment by PremiereSetups** [comment]
> 

http://luigical.me/images/Screenshot_06_08_IOk7Ywggae.png

Sadly yours didn't work for me either.

**Comment by PremiereSetups** [comment]
> I made a fork, you can install it Install link: https://github.com/RilyEvent/BungeeGuard/suites/6847775715/artifacts/264257362 Build log: https://github.com/RilyEvent/BungeeGuard/actions/runs/2462749036


Sadly yours didn't work either, http://luigical.me/images/Screenshot_06_08_IOk7Ywggae.png

**Comment by xHyroM** [comment]
> > I made a fork, you can install it Install link: https://github.com/RilyEvent/BungeeGuard/suites/6847775715/artifacts/264257362 Build log: https://github.com/RilyEvent/BungeeGuard/actions/runs/2462749036
> 
> Sadly yours didn't work either, http://luigical.me/images/Screenshot_06_08_IOk7Ywggae.png

what is your java version? it works fine for me

**Comment by PremiereSetups** [comment]
> > > I made a fork, you can install it Install link: https://github.com/RilyEvent/BungeeGuard/suites/6847775715/artifacts/264257362 Build log: https://github.com/RilyEvent/BungeeGuard/actions/runs/2462749036
> > 
> > 
> > Sadly yours didn't work either, http://luigical.me/images/Screenshot_06_08_IOk7Ywggae.png
> 
> what is your java version? it works fine for me

Java 17, Newest bungeecord

**Comment by NoltoxGit** [comment]
@lucko the new build doesn't work.
Error: https://pastebin.com/FJKNYr2Q

**Comment by PremiereSetups** [comment]
I also am getting an error on the new version:
http://luigical.me/images/Screenshot_06_08_mss6K7oKY4.png

**Comment by lucko** [comment]
Read the release note - it only supports BungeeCord 1.19.

**Comment by PremiereSetups** [comment]
> Read the release note - it only supports BungeeCord 1.19.

Yeah that is on the newest, just redownloaded to confirm, I am getting the .jar from here: https://ci.md-5.net/job/BungeeCord/lastBuild/

http://luigical.me/images/Screenshot_06_08_DOZrO9NfDB.png

Let me know if I am missing something here?

**Comment by lucko** [comment]
Try using Java 11.

**Comment by PremiereSetups** [comment]
> Try using Java 11.

That fixed it, I was using Java 8 before. Thank you!
