### ISSUE TITLE
BungeeGuard 1.19 error

### ISSUE THREAD

**Issue by PasteDev** [lucko/BungeeGuard#77]
[BungeeGuard] Denying connection from *.*.*.* - MTYxLjEyOS4xODEuMTg= - reason: INVALID_HANDSHAKE

LOG: https://bin.bloom.host/reyoyonifo

![image](https://user-images.githubusercontent.com/42726698/173119880-ab13d026-f928-4f9d-8829-5166df56bc86.png)

![image](https://user-images.githubusercontent.com/42726698/173119915-ab5bda02-89fd-4401-8415-56f0372ce91a.png)

**Comment by stijnb1234** [comment]
Send the contents of your config, with your token removed.

**Comment by PasteDev** [comment]
> 

https://bin.bloom.host/jalubemuge.makefile

**Comment by lucko** [comment]
Is BungeeGuard installed + enabled on your proxy?
