### ISSUE TITLE
Players can bypass

### ISSUE THREAD

**Issue by ZoneTriplu** [lucko/BungeeGuard#8]
Paperspigot configuration BungeeGuard:

> # BungeeGuard Configuration
> 
> # Allowed authentication tokens.
> allowed-tokens:
>   - "DEoezLcojw6kHYZWnTNrghPW7BzxYXrbNlnPdL6jdkuuARnH8WmJYgNuCxLGByY1"
> 
> 
> # Messages
> no-data-kick-message: "&cUnable to authenticate - no data was forwarded by the proxy."
> no-properties-kick-message: "&cUnable to authenticate."
> invalid-token-kick-message: "&cAn invalid authentication token was provided."

BungeeCord configuration BungeeGuard:
token: DEoezLcojw6kHYZWnTNrghPW7BzxYXrbNlnPdL6jdkuuARnH8WmJYgNuCxLGByY1

Informations:
Im not using Spigot, im using PaperSpigot
Im not using SkinRestored

Players can enter on skyblock without acces the BungeeCord, can you help me please?

**Comment by lucko** [comment]
You need to use Paper.
https://papermc.io/

BungeeGuard does not support Spigot.
