### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by PiweeX** [lucko/BungeeGuard#87]
[11:31:10] [main/ERROR]: Unable to load plugin plugins/BungeeGuard.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.

**Comment by stijnb1234** [comment]
BungeeGuard is built in to Velocity already. No need to install it yourself. 😉

**Comment by stijnb1234** [comment]
Also checkout https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity

**Comment by rautamiekka** [comment]
Velocity is superior to Bungeecord in every way anyway, BungeeGuard just makes Bungeecord less of a security risk.

Should read the Velocity docs, too.

**Comment by PiweeX** [comment]
> Also checkout https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity

So I don't have to install BungeeGuard on a velocity server?

Because, on backend servers (paper) he asks me for a token from the Velocity configuration

![download](https://user-images.githubusercontent.com/33425430/179027666-2bcb6efc-a7fe-499c-b27c-abef3efbdc01.png)


otherwise my velocity server, from 1.7x to 1.19x

Sorry to disturb you. I'd just like to fix this as soon as possible because someone managed to get on to the backhand server without a lobby

**Comment by PiweeX** [comment]
> Also checkout https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity

Thank you! I got it

I didn't understand because the folder wasn't created by the addition of plugin, i should have read the dosc better


I'm only interested in whether I need to generate my token in some way or put it the same as 
https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity

![download](https://user-images.githubusercontent.com/33425430/179029691-4650a261-0e7e-4b98-bcc8-c9fb6e4e9efa.png)

**Comment by PiweeX** [comment]
> > Also checkout https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity
> 
> Thank you! I got it
> 
> I didn't understand because the folder wasn't created by the addition of plugin, i should have read the dosc better
> 
> I'm only interested in whether I need to generate my token in some way or put it the same as https://github.com/lucko/BungeeGuard/blob/master/INSTALLATION.md#if-you-are-using-velocity
> 
> ![download](https://user-images.githubusercontent.com/33425430/179029691-4650a261-0e7e-4b98-bcc8-c9fb6e4e9efa.png)

I put the token listed there but it's invalid, how can I generate my token? I can't find a dosc anywhere

[16:38:42 WARN]: [BungeeGuard] Denying connection from 172.18.0.1 - a200530310-c918-313321-ba6e-84cdcf469a13 @ Mq4LjaIyMCxyMxQcsA== - YhpsLWwVWrNnNgQch5 - reason: INCORRECT_TOKEN

**Comment by lucko** [comment]
The token for BungeeGuard is the same as the forwarding secret in the velocity config.

**Comment by Logikoz** [comment]
[05:50:35 ERROR]: Unable to load plugin plugins/BungeeGuard.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]

**Comment by rautamiekka** [comment]
> [05:50:35 ERROR]: Unable to load plugin plugins/BungeeGuard.jar com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins. at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]

Did you read the thread ? Velocity ain't Paper (that's why BungeeGuard doesn't run), and like I already said, you don't use Velocity together with a plugin intended for Bungeecord.

**Comment by Logikoz** [comment]
> > [05:50:35 ERROR]: Unable to load plugin plugins/BungeeGuard.jar com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins. at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)] at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
> 
> Did you read the thread ? Velocity ain't Paper (that's why BungeeGuard doesn't run), and like I already said, you don't use Velocity together with a plugin intended for Bungeecord.

What you said doesn't make any sense...

The log I sent above was caused by a velocity proxy (which should have support).

I used bungeecord together with bungeeguard without any problems, but as soon as I created another proxy using velocity, bungeeguard no longer works.
